### ISSUE TITLE
Make markers filterable based on title/credential?

### ISSUE THREAD

**Issue by jamesaspence** [twotoasters/clusterkraf#42]
Is there any ability to filter the markers currently being shown? I need to filter the markers that are shown/clustered, with the ability to also remove that filter and show every marker. Is that possible in the library? I tried to add a delete method to the library in order to remove markers from the clusters (to go in hand with the add method), but the clustering didn't seem to update at all.

**Comment by maximou4391** [comment]
Hello,
I joined @jamesaspence question. Is there a way to filter based on some criteria or do we have to re - init the cluster object with a fresh set of already filtered data?

Regards,

Maxime.

**Comment by curtinmartis** [comment]
@maximou4391 Unfortunately, the company that used to maintain this repo (Two Toasters) is no longer around, and this repo isn't actively supported. If you need to support clustering I'd recommend using Google's [Android Maps Utils library](https://github.com/googlemaps/android-maps-utils), though it's not perfect.

**Comment by maximou4391** [comment]
Ok thanks anyway for the quick reply!
Have a good day.
